gnutix_twig:
    assets_dir: %app.web_dir%
    templates_paths:
        - %app.web_dir%/views
    options:
        strict_variables: true

gnutix_library:
    source_file_path: %app.root_dir%/data/books.xml
