gnutix_twig:
    assets_dir: %kernel.web_dir%
    templates_paths:
        - %kernel.web_dir%/views
    options:
        strict_variables: true

gnutix_library:
    source_file_path: %kernel.app_root_dir%/data/books.xml
