services:

    #
    # Twig templating
    #

    twig:
        alias: twig.environment

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [ %twig.templates_locations% ]

    twig.environment:
        class: Twig_Environment
        arguments: [ @twig.loader, %twig.options% ]
