imports:
    - { resource: services.yml, ignore_errors: true }

services:
    gnutix_library.loader:
        alias: gnutix_library.loader.yaml_file_loader

    gnutix_library.library_factory:
        alias: gnutix_library.library_factory.yaml_library_factory
