imports:
    - { resource: ../src/Gnutix/Library/DependencyInjection/services.yml }
    - { resource: ../src/Gnutix/StarWarsLibrary/DependencyInjection/services.yml }

# Twig configuration
gnutix_twig:
    templates_paths:
        - %kernel.root_dir%/web/views
    options:
        # @todo Activate this once in production
        # cache: %kernel.root_dir%/cache/twig

# Library configuration
gnutix_library:
    source_file_path: %kernel.root_dir%/data/books.xml
