imports:
    - { resource: ../src/Gnutix/Library/DependencyInjection/services.yml }
    - { resource: ../src/Gnutix/StarWarsLibrary/DependencyInjection/services.yml }

gnutix_twig:
    templates_paths:
        - %kernel.root_dir%/web/views
    options:
        strict_variables: true

gnutix_library:
    source_file_path: %kernel.root_dir%/data/books.xml
