imports:
    - { resource: config_dev.yml }

gnutix_library:
    source_file_path: %kernel.root_dir%/data/fixtures/library.fixtures.yml

services:
    gnutix_library.loader:
        alias: gnutix_library.loader.yaml_file_loader

    gnutix_library.library_factory:
        alias: gnutix_library.library_factory.yaml_library_factory
